### ISSUE TITLE
Update the url for the spawn-fcgi package on code-server and r-studio images

### ISSUE THREAD

**Issue by atheo89** [opendatahub-io-contrib/workbench-images#28]
The [R Studio](https://github.com/opendatahub-io-contrib/workbench-images/blob/main/rstudio/container/Dockerfile#L87) and[ Code Server](https://github.com/opendatahub-io-contrib/workbench-images/blob/main/code-server/container/Dockerfile#L55) Dockerfiles are using an obsolete URL to fetch the spawn-fcgi package. 

You may update it to: `https://www.rpmfind.net/linux/fedora/linux/releases/37/Everything/x86_64/os/Packages/s/spawn-fcgi-1.6.3-23.fc37.x86_64.rpm`

**Comment by guimou** [comment]
Fixed in #30
